### ISSUE TITLE
forsenga and doctor pepega

### ISSUE THREAD

**Issue by roboaaron1** [Alycse/PepegaCatch#13]
Sorry to bug you again, i just wanted to tell you that when you catch doctor pepega, it gives you forsenga, and when you get doctor pepega, you get forsenga. I hope you can fix this glitch soon. Keep up the good work, and congrats on 100 players.

**Comment by Alycse** [comment]
Don't worry haha, I want my users to report bugs and give feedback.
The Forsenga/Doctor Pepega bug should be fixed in the next update. As usual though, since Google takes a long time to approve extension updates, it's gonna take a few days before this update gets published. I'm really sorry for the inconvenience!
And again, thanks for taking the time to report!
